### PR TITLE
ENH: additional unittest with embedded tag being not at the beginning

### PR DESCRIPTION
**Pull request by yarikoptic**
passes! ;)

### CODE REVIEW

**Comment by yarikoptic** [comment]
btw -- why you didn't just accept my PR?  it would have automatically being added to your PR -- instead you seems have redone it manually

**Comment by sebres** [comment]
<blockquote>instead you seems have redone it manually</blockquote>

because It is not really your test case :)
I have found a "bug" (`startswith/endswith` replaced it with `re.search` ...), so your test example is enclosed in my test case, but in addition checks "string contains not replaced tags"...

**Comment by yarikoptic** [comment]
> because It is not really your test case :)

brr -- but I have tried so hard to contribute to your test case !  that is the point of PRs is to contribute to others ;)
yeah -- your improved upon mine is overall a win ;)

**Comment by sebres** [comment]
<blockquote>but I have tried so hard to contribute to your test case</blockquote>

Add yourself to the Thx ;)

**Comment by yarikoptic** [comment]
On Wed, 21 Jan 2015, Serg G. Brester wrote:

> ```
>  but I have tried so hard to contribute to your test case
> ```
> 
>    Add yourself to the Thx ;)

LOL ;)  did already.... but 'git shortlog -sn' is lacking ;)

**Pull request closed without merging**
