### PR TITLE
RF: adjusted few method names to reflect that they return logs not paths

### PR DESCRIPTION
**Pull request by yarikoptic**
Also for using log vs container for consistency

While we are at this fix ;-)

### CODE REVIEW

**Comment by sebres** [comment]
Unfortunately that will conflict with all my feature branches... :(

**Comment by yarikoptic** [comment]
any particular common point? may be it could facilitate finally picking up those interesting pieces and furnishing them as atomic PRs for the common good? ;) (I remember the one really lovely one speeding up testing...)

**Comment by sebres** [comment]
Well, if I develop inside a community, I try always to avoid such renaming (only for renaming purposes).
In conclusion we are not alone and my fork certainly is not the only.
By private members and if the line was anyway changed - maybe ok, but not the public methods... It's simple bad manners :)
But, I will see later what I can do here...

**Comment by yarikoptic** [comment]
On Thu, 03 Dec 2015, Serg G. Brester wrote:

> Well, if I develop inside a community, I try always to avoid such renaming
> (only for renaming purposes).
> In conclusion we are not alone and my fork certainly is not the only.
> By private members and if the line was anyway changed - maybe ok, but not the
> public methods... It's simple bad manners :)

yeah -- if there is anyone using fail2ban as a module.  are you aware of
such uses ? (not forks, but really uses from outside apps)

we could easily provide deprecation cycle with appropriate warnings to
remove them in e.g. 0.10

> But, I will see later what I can do here...

## coolio

Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by sebres** [comment]
Resolving all the conflicts in https://github.com/sebres/fail2ban/tree/f2b-perfom-prepare-716 taken up to 2 hours. 
Still 2 branches... :( fortunately based on this one.

**Comment by yarikoptic** [comment]
Sorry about that. What could be the next atomic piece we could pick up into mainline? Those tests speedups may be?

**Pull request merged**
